Accounts/urls.py
from django.urls import path
from .views import *

app_name = 'Accounts'
urlpatterns = [
    path('login/', loginPage, name='login'),
    path('signup/', registerPage, name='sign-up'),
    path('logout/', logoutUser, name='logout'),
    path('profile/', Profile_view, name='profile'),
    path('forget_password/', resetpassword_view, name='reset'),
]

Elibrary/urls.py
from django.contrib import admin
from django.urls import path,include
from Resources.views import home_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('Resources/', include('Resources.urls')),
    path('Accounts/', include('Accounts.urls')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

admin.site.site_header='Nuesa Digital library'
admin.site.index_title='Nuesa E-library'

Resources/urls.py
from django.urls import path
from .views import *

app_name = 'Resources'
urlpatterns = [
    path('', home_view, name='departments'),
    path('<int:id>/<str:level>/', department_view, name='department'),
    # path('update_item/', updateItem, name='update_item'),
    # path('delete_item/', delete_item, name='delete_item'),
    # path('review_item/', review_item, name='review_item'),
    # path('like/', like_book, name='like_book'),
]

Resources/templates/department.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Begin Page Content -->
<div class="tabContainer container-fluid">
    <!-- Page Heading -->
    <div class="d-flex align-items-center ">
        <img src="{% static 'img/Nuesa Logo.jpg' %}" alt="" class="img-fluid brandlogo me-3">
        <div>
            <h1 class="h3 mb-2 text-gray-800 text-uppercase">{{ Department.Name }} Engineering</h1>
            <div class="rule"></div>
            <div class="h6"> {{level}} level Resources</div>
            <div class="btn-group mb-2">
                <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    Switch Level
                </button>
                <ul class="dropdown-menu">              
                    <li> <a class="dropdown-item" href="{% url 'Resources:department'  Department.id 100 %}">100</a></li>
                    <li><a class="dropdown-item" href="{% url 'Resources:department'  Department.id 200 %}">200</a></li>
                    <li><a class="dropdown-item" href="{% url 'Resources:department'  Department.id 300 %}">300</a></li>
                    <li><a class="dropdown-item" href="{% url 'Resources:department'  Department.id 400 %}">400</a></li>
                    <li><a class="dropdown-item" href="{% url 'Resources:department'  Department.id 500 %}">500</a></li>
                </ul>
            </div>
        </div>

    </div>

    <ul class="buttonContainer nav nav-pills my-3">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" onclick="showPanel(0)" style="cursor:pointer;">E-textbook</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" onclick="showPanel(1)" style="cursor:pointer;">Past Questions</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" onclick="showPanel(2)" style="cursor:pointer;">Materials</a>
        </li>
    </ul>


    <!-- Example single danger button -->




    <div class="tabPanel E_textbook_Wrapper" style="display: none;">
        {% if not Etextbooks %}
        <div class="no_textbook_container mt-3">
            <h5> Textbooks are not available at the moment, Please check back later</h5>
        </div>
        {% else %}
        <div class="mb-3">
            <form class="d-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                <div class="input-group">
                    <input id="searchbar2" type="text" class="form-control border-0 small" placeholder="Search for..."
                        aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                        <button id="search2" class="btn btn-primary" type="button">
                            <i class="fas fa-search fa-sm"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>



        <div class="dept row ">
            <!-- Mechanical Engineering -->
            {% for textbook in Etextbooks %}
            <div id="departmentcard1" class="col-xl-3 col-md-6 mb-4">
                <div class="card  shadow h-100 py-2">
                    <div class="card-body d-flex flex-column align-items-center">
                        <img src="{{ textbook.TextbookimageURL }}" alt="" class="img-fluid mb-3 shadow-sm">
                        <h4 id="departmentname1" class="h6 mb-2 text-center">{{ textbook.Title }}</h4>
                        <a href="{{ textbook.File.url }}" class="btn btn-primary" download>download <i
                                class="fa-solid fa-download"></i></a>
                    </div>
                </div>
            </div>
            {% endfor %}

            <div>

            </div>

            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    {% if Etextbooks.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
                    <li class="page-item"><a class="page-link"
                            href="?page={{ Etextbooks.previous_page_number }}">Previous</a></li>
                    {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                    {% endif %}
                    {% for num in nums %}
                    <li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}"
                            data-counter="{{ forloop.counter }}"> {{ forloop.counter }}</a></li>
                    {% endfor %}
                    {% if Etextbooks.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{Etextbooks.next_page_number}}">next</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="?page={{ Etextbooks.paginator.num_pages }}">Last
                            &raquo;</a></li>
                    {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">next</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
        {% endif %}


    </div>

    <div class="tabPanel Past_Question_wrapper" style="display: none;">
        <div class="card shadow mb-4 ">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Past Questions Table</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Course</th>
                                <th>year</th>
                                <th>download</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for question in Pastquestion %}
                            <tr>
                                <td>{{ question.course }}</td>
                                <td>{{ question.year }}</td>
                                <td><a href="{{ question.File.url }}" class="btn btn-primary" download>download</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="tabPanel Material_wrapper" style="display: none;">
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary"> Materials Tables</h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped" id="dataTables" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Course</th>
                                <th>Title</th>
                                <th>download</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if not materials %}
                            <tr>
                                <td colspan="3"> No Materials Yet , Check Back later</td>
                            </tr>
                            {% else %}
                            {% for material in materials %}
                            <tr>
                                <td>{{ material.course }}</td>
                                <td>{{ material.Title }}</td>
                                <td><a href="{{ material.File.url }}" class="btn btn-primary"
                                        download="{{ material.File.url }}">download</a> </td>
                            </tr>
                            {% endfor %}
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
<script src="{% static 'js/sb-admin-2.min.js' %}"></script>
<script src="{% static 'js/Home.js' %}"></script>
<!-- Page level plugins -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
<script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
<!-- Page level custom scripts -->
<script src="{% static 'js/demo/datatables-demo.js' %}"></script>


{% endblock %}