Accounts/urls.py
from django.urls import path
from .views import *

app_name = 'Accounts'
urlpatterns = [
    path('login/', loginPage, name='login'),
    path('signup/', registerPage, name='sign-up'),
    path('logout/', logoutUser, name='logout'),
    path('profile/', Profile_view, name='profile'),
    path('forget_password/', resetpassword_view, name='reset'),
]

Elibrary/urls.py
from django.contrib import admin
from django.urls import path,include
from Resources.views import home_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('Resources/', include('Resources.urls')),
    path('Accounts/', include('Accounts.urls')),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

admin.site.site_header='Nuesa Digital library'
admin.site.index_title='Nuesa E-library'

Accounts/models.py
from django.db import models

# Create your models here.

Accounts/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from student.models import Student


class CreateUserForm(UserCreationForm):
    class Meta:
        model =User
        fields=['username','email','password1','password2']

class ProfileForm(ModelForm):
    class Meta:
        model = Student
        fields = '__all__'
        exclude = ['User']
        widgets={
            'profileimage': forms.FileInput(attrs={'class':"form-control"}),
            'FirstName': forms.TextInput(attrs={'class':"form-control"}),
            'LastName': forms.TextInput(attrs={'class':"form-control"}),
            'Gender': forms.Select(attrs={'class':"form-select"}),
            'department': forms.Select(attrs={'class':"form-select"}),
            'Level': forms.Select(attrs={'class':"form-select"}),
        }

Accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import *
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from Resources.models import *
from student.models import *


def loginPage(request):
    if request.user.is_authenticated:
        return redirect('home')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password =request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                try:
                    student=Student.objects.get(User=request.user)
                    return redirect('home')
                except:
                    Student.objects.create(User=request.user)
                    return redirect("Accounts:profile")

            else:
                messages.info(request, 'Username OR password is incorrect')
    context = {}
    return render(request, 'login.html', context)

def registerPage(request):
    Departments=department.objects.all()
    if request.user.is_authenticated:
        return redirect('home')
    else:
        form = CreateUserForm()
        if request.method == 'POST':
            form=CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                Username = form.cleaned_data.get('username')
                messages.success(request, 'Account have been created for you' + Username)
                return redirect('Accounts:login') #Redirect Calls on the Url function directory            
    context={
        "form":form
    }
    return render(request,'register.html',context)

def Profile_view(request):
    user=request.user.student
    form=ProfileForm(instance=user)
    Departments=department.objects.all()
    context={
       "Departments":Departments,
       "form":form,
    }
    if request.method == 'POST':
        form=ProfileForm(request.POST,request.FILES,instance=user)
        if form.is_valid():
            form.save()
        # Firstname = request.POST.get('Firstname')
        # Lastname = request.POST.get('Lastname')
        # dept = request.POST.get('dept')
        # Dept=department.objects.get(id=dept)
        # Level = request.POST.get('Level')
        # Gender = request.POST.get('Gender')
        # file =request.FILES['file']
        # if file == "":
        #     student=Student.objects.create(User=user,FirstName=Firstname,LastName=Lastname,department=Dept,Level=Level,Gender=Gender)
        # else:
        #     student=Student.objects.create(User=user,FirstName=Firstname,LastName=Lastname,department=Dept,Level=Level,Gender=Gender,profileimage=file)
        # student.save()
            messages.success(request, 'your Profile was updated Successfully')
            return redirect('Accounts:login')
        # except:
        #     messages.error(request, 'Check your input and try again')
        #     return render(request,"Profile.html",context)
     
    
    return render(request,"Profile.html",context)

def logoutUser(request):
	logout(request)
	return redirect('Accounts:login')

def resetpassword_view(request):
    context = {
    }
    return render(request, 'forgot-password.html', context)

Accounts/templates/Profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title> Profile</title>

    <!-- Custom fonts for this template-->
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/Nuesa Logo.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/Nuesa Logo.png' %}">
    <link rel="icon" type="image/png" sizes="48x48" href="{% static 'img/Nuesa Logo.png' %}">
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">
    <link href="{% static 'css/Home.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <div>
                                    <img src="{% static 'img/Nuesa Logo.jpg' %}" alt="" class="img-fluid brandlogo mb-2"
                                        width="85">
                                </div>
                                <h1 class="h4 text-gray-900 mb-4">Update your Profile!</h1>
                            </div>


                            {% if messages %}
                            {% for message in messages %}
                            <div class="alert  {{ message.tags }} alert-dismissible fade show" role="alert">
                                  {{ message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                    aria-label="Close"></button>
                            </div>
                            {% endfor %}
                            {% endif %}
                            <div class="d-flex justify-content-center" style="max-width:500px">
                                <form class="user" method="POST" action="" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <!-- <div class="form-group row">
                                        <div class="col-sm-6 mb-3 mb-sm-0">
                                            <input name="Firstname" type="text" class="form-control form-control-user"
                                                id="exampleFirstName" placeholder="First Name" maxlength="150" required>
                                        </div>
                                        <div class="col-sm-6">
                                            <input name="Lastname" type="text" class="form-control form-control-user"
                                                id="exampleLastName" placeholder="Last Name" maxlength="150" required>
                                        </div>
    
                                    </div>
    
                                    <div class="form-group row">
                                        <div class="col-sm-6 mb-3 mb-sm-0">
                                            <select class="form-select form-control-user" aria-label="Default select example" required name="dept">
                                                <option selected value="">Select your department</option>
                                                {% for Department in Departments %}
                                                <option value="{{ Department.id }}">{{ Department.Name }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                        <div class="col-sm-6">
                            
                                            <select class="form-select form-control-user" aria-label="Default select example" required name="Level">
                                                <option selected value="">Select your Level...</option>
                                                <option value="100">100</option>
                                                <option value="200">200</option>
                                                <option value="300">300</option>
                                                <option value="400">400</option>
                                                <option value="500">500</option>
                                            </select>
                                        </div>
                                    </div>
    
                                    <div class="form-group row">
                                        <div class="col-sm-6 mb-3 mb-sm-0">
                                            <div class="form-check">
                                                <input class="form-check-input" type="radio" name="Gender" id="flexRadioDefault1" value="Male" checked>
                                                <label class="form-check-label" for="flexRadioDefault1">
                                                  Male
                                                </label>
                                              </div>
                                              <div class="form-check">
                                                <input class="form-check-input" type="radio" name="Gender" id="flexRadioDefault2" value="Female">
                                                <label class="form-check-label" for="flexRadioDefault2">
                                                 Female
                                                </label>
                                              </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <p>Upload a good Profile Picture</p>
                                            <div class="input-group mb-3">
                                                <input type="file" class="form-control" id="inputGroupFile02" name="file">
                                            </div>
                                        </div>
                                    </div> -->
                                    <button class="btn btn-primary btn-user btn-block" type="submit" value="submit">Update
                                        Profile</button>
                                    <!-- <hr>
                                    <a href="index.html" class="btn btn-google btn-user btn-block">
                                        <i class="fab fa-google fa-fw"></i> Register with Google
                                    </a>
                                    <a href="index.html" class="btn btn-facebook btn-user btn-block">
                                        <i class="fab fa-facebook-f fa-fw"></i> Register with Facebook
                                    </a> -->
                                </form>
                            </div>
                            
                
        
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <script>
        var errorlist = document.querySelector(".errorlist")
        errorlist.classList.add('bg-danger')
    </script>
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
        </script>
    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>


</body>

</html>

Accounts/templates/forgot-password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title> Forgot Password</title>

    <!-- Custom fonts for this template-->
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/Nuesa Logo.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/Nuesa Logo.png' %}">
    <link rel="icon" type="image/png" sizes="48x48" href="{% static 'img/Nuesa Logo.png' %}">
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                                        <p class="mb-4">We get it, stuff happens. Just enter your email address below
                                            and we'll send you a link to reset your password!</p>
                                    </div>
                                    <form class="user">
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user"
                                                id="exampleInputEmail" aria-describedby="emailHelp"
                                                placeholder="Enter Email Address...">
                                        </div>
                                        <a href="#" class="btn btn-primary btn-user btn-block">
                                            Reset Password
                                        </a>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'Accounts:sign-up' %}">Create an Account!</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'Accounts:login' %}">Already have an account? Login!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js ' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'endor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

Accounts/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>E-library - Login</title>

    <!-- Custom fonts for this template-->
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/Nuesa Logo.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/Nuesa Logo.png' %}">
    <link rel="icon" type="image/png" sizes="48x48" href="{% static 'img/Nuesa Logo.png' %}">
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">
    <link href="{% static 'css/Home.css' %}" rel="stylesheet">

</head> 

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <div>
                                            <img src="{% static 'img/Nuesa Logo.jpg' %}" alt="" class="img-fluid brandlogo mb-2" width="85">
                                        </div>
                                        <h1 class="h4 text-gray-900 mb-4">Login to Explore !</h1>
                                    </div>
                                    {% if messages %}
                                    {% for message in messages %}
                                    <div class="alert  {{ message.tags }} alert-dismissible fade show" role="alert">
                                          {{ message }}
                                        <button type="button" class="btn-close" data-bs-dismiss="alert"
                                            aria-label="Close"></button>
                                    </div>
                                    {% endfor %}
                                    {% endif %}
                                    <form class="user" method="POST" action="">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <input type="text" class="form-control form-control-user"
                                                id="exampleInputEmail" aria-describedby="emailHelp"
                                                placeholder="Enter your username ..." name="username">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"
                                                id="exampleInputPassword" placeholder="Password" name="password">
                                        </div>
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox small">
                                                <input type="checkbox" class="custom-control-input" id="customCheck">
                                                <label class="custom-control-label" for="customCheck">Remember
                                                    Me</label>
                                            </div>
                                        </div>
                                        <input class="btn btn-primary btn-user btn-block" type="submit" value="Login">
            
                                        <!-- <hr>
                                        <a href="index.html" class="btn btn-google btn-user btn-block">
                                            <i class="fab fa-google fa-fw"></i> Login with Google
                                        </a>
                                        <a href="index.html" class="btn btn-facebook btn-user btn-block">
                                            <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook
                                        </a> -->
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'Accounts:reset' %}">Forgot Password?</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'Accounts:sign-up' %}">Create an Account!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>
    <script>
        
    </script>
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
	integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
	</script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

Accounts/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>E-library- Register</title>

    <!-- Custom fonts for this template-->
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/Nuesa Logo.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/Nuesa Logo.png' %}">
    <link rel="icon" type="image/png" sizes="48x48" href="{% static 'img/Nuesa Logo.png' %}">
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">
    <link href="{% static 'css/Home.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <div>
                                    <img src="{% static 'img/Nuesa Logo.jpg' %}" alt="" class="img-fluid brandlogo mb-2" width="85">
                                </div>
                                <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
                            </div>


                            {{ form.errors }}
                            <form class="user" method="POST" action="">
                                {% csrf_token %}
                                <div class="form-group ">
                                    <div class=" mb-3 mb-sm-0">
                                        <input name="username" type="text" class="form-control form-control-user" id="exampleFirstName"
                                            placeholder="User Name" maxlength="150" >
                                    </div>
                                </div>
                                <div class="form-group">
                                    <input type="email"  name="email" class="form-control form-control-user" id="exampleInputEmail"
                                        placeholder="Email Address" maxlength="254">
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <input type="password" name="password1" class="form-control form-control-user"
                                            id="exampleInputPassword" placeholder="Password">
                                    </div>
                                    <div class="col-sm-6">
                                        <input type="password" name="password2" class="form-control form-control-user"
                                            id="exampleRepeatPassword" placeholder="Repeat Password">
                                    </div>
                                </div>
                                <button class="btn btn-primary btn-user btn-block" type="submit" value="submit">Register Account</button>
                                <!-- <hr>
                                <a href="index.html" class="btn btn-google btn-user btn-block">
                                    <i class="fab fa-google fa-fw"></i> Register with Google
                                </a>
                                <a href="index.html" class="btn btn-facebook btn-user btn-block">
                                    <i class="fab fa-facebook-f fa-fw"></i> Register with Facebook
                                </a> -->
                            </form>
                            <hr>
                            <div class="text-center">
                                <a class="small" href="{% url 'Accounts:reset' %}">Forgot Password?</a>
                            </div>
                            <div class="text-center">
                                <a class="small" href="{% url 'Accounts:login' %}">Already have an account? Login!</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <script>
        var errorlist = document.querySelector(".errorlist")
        errorlist.classList.add('bg-danger')
    </script>
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
	integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
	</script>
    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
    

</body>

</html>